### ISSUE TITLE
Keep Raspberry Pi From Entering Sleep Mode

### ISSUE THREAD

**Issue by millenniallglyphs** [GD399-OSD/open-for-discourse#1]
Keeping the Raspberry Pi awake is a crucial first step in developing a functional public display board.

**Comment by bjornmeansbear** [comment]
does this work: https://raspberrypi.stackexchange.com/questions/4773/raspberry-pi-sleep-mode-how-to-avoid#6670 ?

**Comment by devinhalladay** [comment]
Looks like the solution @bjornmeansbear linked worked. Thanks!!

**Comment by bjornmeansbear** [comment]
Awesome!
