### ISSUE TITLE
get more pink tape

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/open-for-discourse#3]
we need more pink tape! I can source this, just adding it here for posterity & accountability.

**Comment by mazzybell** [comment]
This comment isn't helpful but I laughed really hard at this issue

**Comment by bjornmeansbear** [comment]
I think the idea of "pink-tape" as some sort of metaphor is funny … I even know what you're talking about and I still had a little laugh …

**Comment by devinhalladay** [comment]
pink tape has been PURCHASED
