### ISSUE TITLE
we need tea. EARL GREY. HOT.

### ISSUE THREAD

**Issue by devinhalladay** [GD399-OSD/open-for-discourse#6]
__H O T__

**Comment by devinhalladay** [comment]
I can do this. Adding for posterity. Will make sure it's __HOT__.

**Comment by millenniallglyphs** [comment]
It might be nice to stock some other comfort items, including hot sauce, napkins, knives, forks, etc.

**Comment by mazzybell** [comment]
are yall ok ?

**Comment by bjornmeansbear** [comment]
is the water for the tea HOT, or is there a spicy version of earl grey?

**Comment by mazzybell** [comment]
https://www.amazon.com/gp/product/B000LKVRQA/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1

**Comment by devinhalladay** [comment]
@bjornmeansbear the water is HOT but I like the idea spicy tea

**Comment by devinhalladay** [comment]
anyways, I bought the tea and it will get here monday so I'm closing this
